### ISSUE TITLE
LipSync 

### ISSUE THREAD

**Issue by Dannysudo** [Qusai-Azzam/Unity3d-IBM-WatsonAPI#1]
Have you gotten it to work with Salsa lipsync? For some reason my UMA model won't lip sync the TTS message when it speaks.

**Comment by Qusai-Azzam** [comment]
@Dannysudo yes I did Integrate it With Salsa and LibSync Libraries, Actually, it works fine with both of them, the Problem in your case In the UMA model Settings.

**Comment by eschles** [comment]
Hello! I am currently having issues with connecting WatsonAPI to my SALSA lipsync setup. I have followed along with Tony Pigram's tutorial and am using Unity 2021 with SALSA/UMA. How was this issue solved in the past?
